/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as OrgSlugLayoutRouteImport } from './routes/$orgSlug/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as OrgSlugIssuesRouteImport } from './routes/$orgSlug/issues'
import { Route as authAuthJoinRouteImport } from './routes/(auth)/_auth.join'
import { Route as authAuthAddAccountRouteImport } from './routes/(auth)/_auth.add-account'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugLayoutRoute = OrgSlugLayoutRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugLayoutRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIssuesRoute = OrgSlugIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OrgSlugLayoutRoute,
} as any)
const authAuthJoinRoute = authAuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAddAccountRoute = authAuthAddAccountRouteImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/$orgSlug/issues': typeof OrgSlugIssuesRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/add-account': typeof authAuthAddAccountRoute
  '/join': typeof authAuthJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/$orgSlug/issues': typeof OrgSlugIssuesRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/add-account': typeof authAuthAddAccountRoute
  '/join': typeof authAuthJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/$orgSlug/issues': typeof OrgSlugIssuesRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/(auth)/_auth/add-account': typeof authAuthAddAccountRoute
  '/(auth)/_auth/join': typeof authAuthJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/test'
    | '/$orgSlug/issues'
    | '/login'
    | '/signup'
    | '/$orgSlug/'
    | '/add-account'
    | '/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/$orgSlug/issues'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/add-account'
    | '/join'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/test'
    | '/$orgSlug/issues'
    | '/(auth)/_auth'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/$orgSlug/'
    | '/(auth)/_auth/add-account'
    | '/(auth)/_auth/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugLayoutRoute: typeof OrgSlugLayoutRouteWithChildren
  TestRoute: typeof TestRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugLayoutRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/issues': {
      id: '/$orgSlug/issues'
      path: '/issues'
      fullPath: '/$orgSlug/issues'
      preLoaderRoute: typeof OrgSlugIssuesRouteImport
      parentRoute: typeof OrgSlugLayoutRoute
    }
    '/(auth)/_auth/join': {
      id: '/(auth)/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof authAuthJoinRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/add-account': {
      id: '/(auth)/_auth/add-account'
      path: '/add-account'
      fullPath: '/add-account'
      preLoaderRoute: typeof authAuthAddAccountRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface OrgSlugLayoutRouteChildren {
  OrgSlugIssuesRoute: typeof OrgSlugIssuesRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugLayoutRouteChildren: OrgSlugLayoutRouteChildren = {
  OrgSlugIssuesRoute: OrgSlugIssuesRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugLayoutRouteWithChildren = OrgSlugLayoutRoute._addFileChildren(
  OrgSlugLayoutRouteChildren,
)

interface authAuthRouteChildren {
  authAuthAddAccountRoute: typeof authAuthAddAccountRoute
  authAuthJoinRoute: typeof authAuthJoinRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAddAccountRoute: authAuthAddAccountRoute,
  authAuthJoinRoute: authAuthJoinRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugLayoutRoute: OrgSlugLayoutRouteWithChildren,
  TestRoute: TestRoute,
  authAuthRoute: authAuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
