/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as OrgIdLayoutRouteImport } from './routes/$orgId/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIdIndexRouteImport } from './routes/$orgId/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as OrgIdIssuesRouteImport } from './routes/$orgId/issues'
import { Route as authAuthJoinRouteImport } from './routes/(auth)/_auth.join'
import { Route as authAuthAddAccountRouteImport } from './routes/(auth)/_auth.add-account'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdLayoutRoute = OrgIdLayoutRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdIndexRoute = OrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgIdLayoutRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdIssuesRoute = OrgIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OrgIdLayoutRoute,
} as any)
const authAuthJoinRoute = authAuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAddAccountRoute = authAuthAddAccountRouteImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/$orgId/issues': typeof OrgIdIssuesRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$orgId/': typeof OrgIdIndexRoute
  '/add-account': typeof authAuthAddAccountRoute
  '/join': typeof authAuthJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/$orgId/issues': typeof OrgIdIssuesRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$orgId': typeof OrgIdIndexRoute
  '/add-account': typeof authAuthAddAccountRoute
  '/join': typeof authAuthJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/$orgId/issues': typeof OrgIdIssuesRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/$orgId/': typeof OrgIdIndexRoute
  '/(auth)/_auth/add-account': typeof authAuthAddAccountRoute
  '/(auth)/_auth/join': typeof authAuthJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgId'
    | '/test'
    | '/$orgId/issues'
    | '/login'
    | '/signup'
    | '/$orgId/'
    | '/add-account'
    | '/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/$orgId/issues'
    | '/login'
    | '/signup'
    | '/$orgId'
    | '/add-account'
    | '/join'
  id:
    | '__root__'
    | '/'
    | '/$orgId'
    | '/test'
    | '/$orgId/issues'
    | '/(auth)/_auth'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/$orgId/'
    | '/(auth)/_auth/add-account'
    | '/(auth)/_auth/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgIdLayoutRoute: typeof OrgIdLayoutRouteWithChildren
  TestRoute: typeof TestRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId': {
      id: '/$orgId'
      path: '/$orgId'
      fullPath: '/$orgId'
      preLoaderRoute: typeof OrgIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId/': {
      id: '/$orgId/'
      path: '/'
      fullPath: '/$orgId/'
      preLoaderRoute: typeof OrgIdIndexRouteImport
      parentRoute: typeof OrgIdLayoutRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId/issues': {
      id: '/$orgId/issues'
      path: '/issues'
      fullPath: '/$orgId/issues'
      preLoaderRoute: typeof OrgIdIssuesRouteImport
      parentRoute: typeof OrgIdLayoutRoute
    }
    '/(auth)/_auth/join': {
      id: '/(auth)/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof authAuthJoinRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/add-account': {
      id: '/(auth)/_auth/add-account'
      path: '/add-account'
      fullPath: '/add-account'
      preLoaderRoute: typeof authAuthAddAccountRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface OrgIdLayoutRouteChildren {
  OrgIdIssuesRoute: typeof OrgIdIssuesRoute
  OrgIdIndexRoute: typeof OrgIdIndexRoute
}

const OrgIdLayoutRouteChildren: OrgIdLayoutRouteChildren = {
  OrgIdIssuesRoute: OrgIdIssuesRoute,
  OrgIdIndexRoute: OrgIdIndexRoute,
}

const OrgIdLayoutRouteWithChildren = OrgIdLayoutRoute._addFileChildren(
  OrgIdLayoutRouteChildren,
)

interface authAuthRouteChildren {
  authAuthAddAccountRoute: typeof authAuthAddAccountRoute
  authAuthJoinRoute: typeof authAuthJoinRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAddAccountRoute: authAuthAddAccountRoute,
  authAuthJoinRoute: authAuthJoinRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgIdLayoutRoute: OrgIdLayoutRouteWithChildren,
  TestRoute: TestRoute,
  authAuthRoute: authAuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
